name: Python

on:
  push:
    branches: [ main ]
    paths:
      - 'py/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'py/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - run: uv build
  ruff-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - run: uv run tox -e ruff-check
  ruff-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - run: uv run tox -e ruff-format
  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - run: uv run tox -e mypy
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - run: uv run tox
